#!/bin/bash

. runtime.env

rm $DAEMON_LAUNCH_DIR/$SCREENSAVER_MONITOR_DAEMON_PLIST
rm -rf "$SCREENSAVER_MONITOR_DAEMON_FOLDER"
rm "$SCREENSAVER_MONITOR_LOG_FOLDER/$SCREENSAVER_MONITOR_LOG_BASE_NAME"*
