#!/bin/bash

. runtime.env

rm -v $DAEMON_LAUNCH_DIR/$SCREENSAVER_MONITOR_DAEMON_PLIST
rm -rfv "$SCREENSAVER_MONITOR_DAEMON_FOLDER"
rm -v "$SCREENSAVER_MONITOR_LOG_FOLDER/$SCREENSAVER_MONITOR_LOG_BASE_NAME"*
