#!/bin/bash

. runtime.env

echo $SCREENSAVER_MONITOR_DAEMON_PLIST

cp -v $SCREENSAVER_MONITOR_DAEMON_PLIST $DAEMON_LAUNCH_DIR
mkdir -vp "$SCREENSAVER_MONITOR_DAEMON_FOLDER"
cp -v $SCREENSAVER_MONITOR_BIN "$SCREENSAVER_MONITOR_DAEMON_FOLDER"
cp -v $SCREENSAVER_MONITOR_WRAPPER "$SCREENSAVER_MONITOR_DAEMON_FOLDER"
